# Generated by Django 2.0.5 on 2018-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='category',
            field=models.CharField(default='easy_talk', max_length=32),
        ),
    ]
